package Project0.Semantic;

public enum TokenType {
    BUILDIN_TYPE, KW_IF, KW_ELSE, KW_WHILE, KW_TRUE, KW_FALSE, KW_THIS, KW_DEFINE, KW_RETURN, KW_SWITCH, KW_CASE, KW_DO,
    KW_CLASS, KW_PUBLIC, KW_PRIVATE, OPEN_PAREN, CLOSE_PAREN, OPEN_SQU, CLOSE_SQU, OPEN_BRAC, CLOSE_BRAC, COLON, COMMA,
    SEMICOLON, OP_PLUS, OP_MINUS, OP_TIMES, OP_DIVISION, OP_AND, OP_OR, OP_NOR, OP_NOT, OP_LNOT, OP_GREATER, OP_LESSER,
    OP_LAND, OP_LOR, OP_GREATER_EQUAL, OP_LESSER_EQUAL, OP_EQUAL, OP_ASSIGN, OP_INCREASE, OP_DECREASE, INTEGER, NUMBER,
    IDENTIFIER, STRING, DOT, BAD_TOKEN, EOF

}